---
title: "analiza cen zboz"
output: html_document
date: "2025-10-20"
---

```{r}
dane=read.table("http://www.kozlowski.pollub.pl/kukurydza.txt", sep="\t",header=TRUE)
head(dane,n=3)
cena=dane$Zamkniecie
plot(cena,col=4, main="Cena kukurydzy",type="l")
```

### Dopasowanie wielomianem stopnia pierwszego

```{r}
t=1:length(cena)
t
mod1=lm(cena~t) #powstaje model
mod1
summary(mod1)
old_par=par(no.readonly=TRUE)
par(mfrow=c(1,2))
plot(cena,col=4, main="Cena kukurydzy",type="l")
abline(mod1,col=2,lwd=2)
plot(mod1$residuals,type="l",main="Reszty")
abline(h=0)
par(old_par)
AIC(mod1)
```

### Dopasowanie wielomianem stopnia drugiego

```{r}
mod2=lm(cena~t + I(t^2))
summary(mod2)
wsp2=coef(mod2) #współczynniki wielomianu
wsp2
predicted2=wsp2[1]+wsp2[2]*t+wsp2[3]*t^2
predicted2_mdl=mod2$fitted.values
mean((predicted2-predicted2_mdl)^2)
par(mfrow=c(1,2))
plot(cena,col=4, main="Cena kukurydzy",type="l")
lines(t,mod2$fitted.values,col=2,lwd=2)
plot(mod2$residuals,type="l",main="Reszty")
abline(h=0)
par(old_par)
AIC(mod2)
```

### Dopasowanie wielomianem stopnia trzeciego

```{r}

#inna metoda
mod3=lm(cena~t + I(t^2)+I(t^3))
x=data.frame(cena,t,t^2,t^3)
head(x)
mod3a=lm(cena~.,data=x)
summary(mod3)
summary(mod3a)
wsp3=coef(mod3)
wsp3
predicted3=wsp3[1]+wsp3[2]*t+wsp3[3]*t^2+wsp3[4]*t^3
predicted3=mod3$fitted.values
par(mfrow=c(1,2))
plot(cena,col=4, main="Cena kukurydzy",type="l")
lines(t,mod3$fitted.values,col=2,lwd=2)
plot(mod3$residuals,type="l",main="Reszty")
abline(h=0)
par(old_par)
AIC(mod3)
```

### Definiowanie funkcji

nazwa_funkcji=function(arg1,arg2,...,argk){

...

return(result)

}

```{r}
wynik=function(szereg,stopien){
  t=1:length(szereg)
  macierz=NULL
  for(i in 1:stopien){
    macierz=cbind(macierz,t^i)}
  
  ramka=data.frame(szereg,macierz)
  model=lm(szereg~.,data=ramka)
  par(mfrow=c(1,3))
  plot(t,szereg,type="l",main=paste("Dopasowanie wiel.st.:",stopien),ylab="PLN",xlab="notowania")
  lines(t,model$fitted.values,col=2,lwd=1.5)
  
  plot(t,model$residuals,type="l",main="Reszty")
  abline(h=0,col=2,lwd=2)
  
  plot(ecdf(model$residuals),main="Dystrybuanta")
  x=seq(from=min(model$residuals), to=max(model$residuals), length.out=500)
  lines(x,pnorm(x,mean=0,sd=sd(model$residuals)),col=4,lwd=2)
  par(mfrow=c(1,1))
  Sys.sleep(1)
  return(AIC(model))
  
  }
wynik(cena,50)
```

### Animacja

```{r}
aic=NULL
for(j in 1:25){
  aic=c(aic,wynik(cena,j))
}
aic
i=1:25
plot(i,aic,type="p",pch=19,main="Wartośći indeksu AKAIKE", xlab="Stopień wielomianu",ylab="Wartości indeksu",col.main="#A2007B", col.axis="#660066", col.lab="#841839")
wynik(cena,stopien=11)
  
```
